name: co2mpas_driver
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - docutils
  - flask
  - schedula>=0.3.2'
  - jupyterlab >=0.35.5,<0.36
  - lxml
  - multiprocess
  - networkx
  - pandas
  - numpy >=1.15
  - openpyxl
  - scipy
  - xlrd
  - pip
  - python >=3.7,<3.8.0a0
  - python-graphviz
  - regex
  - plotly
  - tornado<6
  - pip:
      - schedula>=0.3.2
      - jupyter-server-proxy