name: co2mpas_driver
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - docutils
  - flask
  - jupyterlab >=0.35.5,<0.36
  - lxml
  - multiprocess
  - networkx >=2.0.0,<2.4
  - pandas
  - pyyaml
  - matplotlib==3.1.0
  - numpy >=1.15
  - openpyxl
  - scipy
  - xlrd
  - pip
  - python >=3.7,<3.8.0a0
  - python-graphviz
  - regex
  - plotly
  - tornado==5.1.1
  - schedula>=0.3.2
  - pip:
      - jupyter-server-proxy